name: Build SQLNA
# manually triggered workflow
on: [workflow_dispatch]
env:
    SOLUTION_FILE_PATH: .\SQL_Network_Analyzer
    BUILD_CONFIGURATION: Release
jobs:
    job1:
      runs-on: windows-latest
      steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      - name: Build It
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:RunCodeAnalysis=False /p:DeleteExistingFiles=True /bl
      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: SQLNA.EXE
          path: "SQL_Network_Analyzer\\SQLNA\\bin\\Debug"
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/1.5.1683.0
          asset_path: ./SQL_Network_Analyzer/SQLNA/bin/Debug/SQLNA.exe
          asset_name: SQLNA.EXE
          asset_content_type: application/octet-stream
